### ISSUE TITLE
Agendav frontend not working

### ISSUE THREAD

**Issue by David-Lor** [nagimov/agendav-docker#3]
Hello there! I'm trying your Docker image, but it seems to be not working. Are you aware of any problem with it?

I've deployed a Radicale server and this image like this:

```bash
docker run -d --name=caldav-radicale -p 5232:5232 tomsquest/docker-radicale
docker run -d --name=caldav-agendav -p 5233:80 -e AGENDAV_CALDAV_SERVER=http://caldav-radicale:5232 -e AGENDAV_SERVER_NAME=caldav-radicale nagimov/agendav-docker
```

When accessing the page, nothing happens; requests return error 500. No errors on container output. Agendav container can reach the Radicale container & server.

```bash
root@2f0e6507faff:/var/log/apache2# cat access.log
192.168.0.211 - - [31/Jan/2022:22:32:29 +0000] "GET / HTTP/1.1" 500 185 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
```

I noticed the following output in the file `/var/log/apache2/davi-error.log`:

```
root@2f0e6507faff:/var/log/apache2# cat davi-error.log 
[Mon Jan 31 22:32:29.455946 2022] [:error] [pid 319] [client 192.168.0.211:47360] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/2022-01-31.log" could not be opened: failed to open stream: Permission denied' in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/GroupHandler.php(67): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\GroupHandler->handle(Array)\n#3 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\\Logger->addRecord(400, 'Uncaught Except...', Array)\n#4 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/ErrorHandler.php(137): Monolog\\Logger->log('error', 'Uncaught Except...', Array)\n#5 [internal function]: Monolog\\ErrorHandler->handleException(Object(Unexp in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Mon Jan 31 22:32:29.456355 2022] [:error] [pid 319] [client 192.168.0.211:47360] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/2022-01-31.log" could not be opened: failed to open stream: Permission denied' in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/GroupHandler.php(67): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\GroupHandler->handle(Array)\n#3 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\\Logger->addRecord(550, 'Fatal Error (E_...', Array)\n#4 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/ErrorHandler.php(181): Monolog\\Logger->log('alert', 'Fatal Error (E_...', Array)\n#5 [internal function]: Monolog\\ErrorHandler->handleFatalError()\n#6 {main} in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
```

**Comment by nagimov** [comment]
Seems like a permission issue to log files/folders. Could you try to rebuild the image with this patch to dockerfile? https://github.com/gasseluk/agendav-docker/commit/a632d3140fd6125915dbc26039e0597a23a5b7a8

**Comment by David-Lor** [comment]
@nagimov Tried that image, but I'm having the same problem, and the same (or similar) output on the `davi-error.log` file

```
[Wed Feb 02 20:32:47.661976 2022] [:error] [pid 426] [client 192.168.0.211:35322] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/2022-02-02.log" could not be opened: failed to open stream: Permission denied' in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/GroupHandler.php(67): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\GroupHandler->handle(Array)\n#3 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\\Logger->addRecord(550, 'Fatal Error (E_...', Array)\n#4 /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/ErrorHandler.php(181): Monolog\\Logger->log('alert', 'Fatal Error (E_...', Array)\n#5 [internal function]: Monolog\\ErrorHandler->handleFatalError()\n#6 {main} in /var/www/agendav/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: http://server.lan:5233/
```

That dockerfile was lacking a `ARG AGENDAV_LOG_DIR` directive (I set it to `/tmp/log`).

**Comment by nagimov** [comment]
This part:
```
The stream or file "/2022-02-02.log" could not be opened
```
indicates that `AGENDAV_LOG_DIR` is not set. Could you retry with `-e AGENDAV_LOG_DIR=/tmp/`?
I'm going to specify that `AGENDAV_LOG_DIR` is mandatory in readme as well
